# Generated by Django 3.2.16 on 2023-09-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20230921_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthday',
            old_name='iamge',
            new_name='image',
        ),
    ]
